import { Poppins } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider
} from '@clerk/nextjs'
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Chattrix",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
     <ClerkProvider>
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Analytics/>
        <SpeedInsights/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}

